@startuml
agent Movie
agent Customer
agent MovieService
agent ProxyService
agent VideoPlayer

Movie -- MovieService
Movie --ProxyService
MovieService -- Customer
Customer -- VideoPlayer
VideoPlayer -- Movie
ProxyService -- Customer
ProxyService -- MovieService
ProxyService -- VideoPlayer
@enduml


